### ISSUE TITLE
Web security checklist

### ISSUE THREAD

**Issue by arroway** [mozilla/mentoring#87]
Hi, 
this is a follow-up of the RRA. Please contact secops for any related question!

[edit: move checklist from @g-k's comment below --dustin]

Risk Management
--------------

Done.

Infrastructure
--------------

No admin panel. Ops will configure TLS.

* [x] Build and deploy main or -slim variants of official language-specific base docker images e.g. [node](https://hub.docker.com/_/node/), [python](https://hub.docker.com/_/python/), or [rust](https://hub.docker.com/_/rust/) and contact secops@ if you want to use other variants

Development
-----------
* [x] Ensure your code repository is configured and located appropriately:
  * [x] Application built internally should be hosted in trusted GitHub organizations mozilla
  * [x] Secure your repository by implementing [Mozilla's GitHub security standard](https://github.com/mozilla-services/GitHub-Audit/blob/master/docs/checklist.md).
* [x] Enable [automated security fix PRs on GitHub](https://help.github.com/en/articles/configuring-automated-security-fixes#managing-automated-security-fixes-for-your-repository) for vulnerabilities in 3rd-party dependencies

I don't think the application risk warrants the other controls.

Dual Sign Off
------------

Does not push data to Fx clients.

Logging
-------
* [x] Publish detailed logs in [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) format (**APP-MOZLOG**) (in #92)
  * Business logic must be logged with app specific codes (see [FxA](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#defined-errors))
  * Access control failures must be logged at WARN level

Web Applications
----------------

* [x] Must have a [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy). (moved to #93)
* [x] Third-party javascript must be pinned to specific versions using [Subresource Integrity (SRI)](https://infosec.mozilla.org/guidelines/web_security#subresource-integrity) (the app hosts everything / is first party)

* [x] Web APIs:
  * [x] must set a non-HTML content-type on all responses, including 300s, 400s and 500s (moved to #94)
  * [x] Should use authentication tokens with a unique pattern which is easily parsed with a regexp. This should allow inclusion into a token scanning service in the future. (E.g. prefix `mgp-` + 20 hex digits would match the regexp `\bmgp-[0-9A-Fa-f]{20}\b`) (does not use auth tokens; django sessions use random value)

The scanning stuff will start once the service metadata is updated.

Security Features
-----------------
* [x] Authentication of Mozillians should be via Auth0/SSO. (already configured)

Not building a core Firefox service.

Databases
---------
* [x] All SQL queries must be parameterized, not concatenated (Django ORM handles this)

* [x] Applications must use accounts with limited GRANTS when connecting to databases
  * In particular, applications **must not use admin or owner accounts**, to decrease the impact of a sql injection vulnerability.

Common issues
-------------
* [x] User data must be [escaped for the right context](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#XSS_Prevention_Rules_Summary) prior to reflecting it (React does this)

* [x] Apply sensible limits to user inputs, see [input validation](https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Input_Validation) (moved to #95)
  * POST body size should be small (<500kB) unless explicitly needed

Not uploading or hosting content from untrusted content.

Django enforce permissions and access controls server-side.

Behind SSO and not using a CDN.

Not handling cryptographic keys.

Not proxying requests from users and users are trusted.

* [x] Do not use `target="_blank"` in external links unless you also use `rel="noopener noreferrer"` (to prevent [Reverse Tabnabbing](https://www.owasp.org/index.php/Reverse_Tabnabbing)) (probably not applicable)

**Comment by djmitche** [comment]
Estimating 8 points here, to be distributed over the work to address any open items.

**Comment by g-k** [comment]
Ugh I need to revisit the checklist.

I don't have access to edit the parent comment, but I'll take a TODO to pare down the checklist to a more manageable size (we can rule out a bunch of that stuff that isn't app functionality or that Django or https://python-dockerflow.readthedocs.io/en/main/django.html already handle), file issues for the stuff I think is relevant, and then comment here with the updated checklist.

edit: oh wait I see Dustin already self-assigned. In that case let me know know if ^ would help.

I filed the linked new service issue in the foxsec repo. I wasn't sure if there are any stage URLs and I assumed the cloud services security component would be fine for security issues.

**Comment by djmitche** [comment]
There's just the one environment for this tool - it's not going to be active or critical enough to need more than that.  I can certainly parse this list just fine, but if you have/create a more refined version I wouldn't complain.  The "8 story points" is probably 1 point to read the list and check most of the boxes, and then 7 to do the things that are relevant and not already complete.

**Comment by g-k** [comment]
Yeah, the user experience leaves a lot to be desired and this checklist was originally written for production Firefox services, which is how we ended up including the kitchen sink. I took a first pass a paring the list down below:

[edit: moved to first comment --dustin]

**Comment by djmitche** [comment]
As a note, the escaping bit might also mention that React handles this automatically in all cases that don't involve the identifier `dangerouslySetInnerHTML`.

**Comment by djmitche** [comment]
Just the limited-grants point left, and I've asked in https://jira.mozilla.com/browse/SE-1483 (which isn't public, sorry)

**Comment by djmitche** [comment]
Limited grants confirmed.  Other changes:
 * admin panel would need to be behind VPN, so we'll just remove it and rely on manual DB manipulation (#109)
 * log retention is 1 year and this is hard to change, so in the absence of anything non-PII to log, we won't add any logging (#92)

Everything's handled in other issues, then.

**Comment by djmitche** [comment]
(and those issue are all now closed)
